### ISSUE TITLE
After selecting an album for playback - songs are not displayed

### ISSUE THREAD

**Issue by vovavvk** [TegraMorgan/MudraMediaPlayer#11]
When selecting an album for playback, music starts to play, but the song list seems empty, while pressing the "empty" list produces a **toast** with a song name.

**Comment by BaselSD** [comment]
Hey,
I've added a toast upon album selection in order to debug the problem... Since I have no watch and I can't insert albums/songs into the emulator I need you to switch to my branch -> run the application -> select an album -> tell me what do you see @TegraMorgan

**Comment by BaselSD** [comment]
new code is ready for testing @TegraMorgan
