### ISSUE TITLE
onBindViewHolder is executed only once instead of once per Album

### ISSUE THREAD

**Issue by vovavvk** [TegraMorgan/MudraMediaPlayer#8]
When debugging I have encountered that onBindViewHolder, that should bind every Album (I have 9) to it's  fragment_item_album.xml instead called only once. Also Albums are not displayed in the MainActivity at all.

**Comment by BaselSD** [comment]
Steps to be taken:
1. Open activity_main.xml
2. Comment the TextView
3. Go to MainActivity.java
4. In the onCreate function: comment the line "albums_text = findViewById(R.id.player_albums);"
5. In the onAlbumsListFragmentInteraction function: Comment "showPlayerButtons()"
6. In the play_music function: Uncomment first two lines and comment the third
7. Comment the onBackPressed
8. Return to activity_main.xml
9. Change the property visibility from invisible to visible in the **3** image views.
10. Run and see If the albums are displayed properly.

We'll proceed after seeing the results
